VenteMobile/VenteMobile/Models/Manufacturier.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace VenteMobile.Models
{
    public class Manufacturier
       : IDisposable
    {
        private bool _disposed = false;
        public int ManufacturierId { get; set; }
        [Required(ErrorMessage = "Le champs est obligatoire")]
        [DataType(DataType.Text)]
        [RegularExpression("[a-zA-Z][a-zA-Z ]+[a-zA-Z]$", ErrorMessage = "Seul les alphabets avec des espaces sont autorisés")]
        [Display(Name = "Marque")]
        public string ManufacturierMarque { get; set; }
        [Required(ErrorMessage = "Le champs est obligatoire")]
        [RegularExpression(@"^(http:\/\/www\.|https:\/\/www\.|http:\/\/|https:\/\/)?[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$", ErrorMessage = "Seul les url sont autorisés")]
        [Display(Name = "SiteWeb")]
        public string ManufacturierSiteWeb { get; set; }
        [Required(ErrorMessage = "Le champs est obligatoire")]
        [DataType(DataType.Text)]
        [RegularExpression("[a-zA-Z][a-zA-Z ]+[a-zA-Z]$", ErrorMessage = "Seul les alphabets avec des espaces sont autorisés")]
        [Display(Name = "Siège social")]
        public string ManufacturierOrigine { get; set; }
        public ICollection<Telephone> Telephones { get; set; } = new HashSet<Telephone>();
        public ICollection<VendeurManufacturier> VendeursManufacturiers { get; set; } = new HashSet<VendeurManufacturier>();
        ~Manufacturier()
        {
            Dispose(false);
        }
        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }
        private void Dispose(bool disposing)
        {
            if (!_disposed)
            {
                if (disposing)
                {

                }
            }
            _disposed = true;
        }
    }
}

VenteMobile/VenteMobile/Controllers/ManufacturiersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PagedList;
using VenteMobile.Data;
using VenteMobile.Models;

namespace VenteMobile.Controllers
{
    public class ManufacturiersController : Controller
    {
        private readonly VenteMobileContext _context;

        public ManufacturiersController(VenteMobileContext context)
        {
            _context = context;
        }


        public async Task<IActionResult> Index(int? page, string sortOrder, string searchString, string currentFilter)
        {
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }


            var Manufacturiers = await Task.Run(() => _context.Manufacturier.Select(x => x));
            if (!string.IsNullOrEmpty(searchString))
            {
                Manufacturiers = await Task.Run(() =>
                _context.Manufacturier.Where(s => s.ManufacturierMarque.Contains(searchString)));

            }
            ViewBag.CurrentFilter = searchString;

            int pageSize = 50;
            int pageNumber = (page ?? 1);
            return View(Manufacturiers.ToPagedList(pageNumber, pageSize));


        }

        // GET: Manufacturiers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var manufacturier = await _context.Manufacturier
                .FirstOrDefaultAsync(m => m.ManufacturierId == id);
            if (manufacturier == null)
            {
                return NotFound();
            }

            return View(manufacturier);
        }
        public async Task<IActionResult> Detail(int? idM, int? idV)
        {
            ViewBag.Vendeur = await _context.Vendeur.FirstOrDefaultAsync(v => v.VendeurId == idV);
            if (idM == null)
            {
                return NotFound();
            }

            var manufacturier = await _context.Manufacturier
                .FirstOrDefaultAsync(m => m.ManufacturierId == idM);
            if (manufacturier == null)
            {
                return NotFound();
            }

            return View(manufacturier);
        }

        // GET: Manufacturiers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Manufacturiers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ManufacturierId,ManufacturierMarque,ManufacturierSiteWeb,ManufacturierOrigine")] Manufacturier manufacturier)
        {
            if (ModelState.IsValid)
            {
                _context.Add(manufacturier);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(manufacturier);
        }

        // GET: Manufacturiers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var manufacturier = await _context.Manufacturier.FindAsync(id);
            if (manufacturier == null)
            {
                return NotFound();
            }
            return View(manufacturier);
        }

        // POST: Manufacturiers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ManufacturierId,ManufacturierMarque,ManufacturierSiteWeb,ManufacturierOrigine")] Manufacturier manufacturier)
        {
            if (id != manufacturier.ManufacturierId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(manufacturier);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ManufacturierExists(manufacturier.ManufacturierId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(manufacturier);
        }

        // GET: Manufacturiers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var manufacturier = await _context.Manufacturier
                .FirstOrDefaultAsync(m => m.ManufacturierId == id);
            if (manufacturier == null)
            {
                return NotFound();
            }

            return View(manufacturier);
        }

        // POST: Manufacturiers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var manufacturier = await _context.Manufacturier.FindAsync(id);
            _context.Manufacturier.Remove(manufacturier);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ManufacturierExists(int id)
        {
            return _context.Manufacturier.Any(e => e.ManufacturierId == id);
        }
    }
}

VenteMobile/VenteMobile/Controllers/VendeurManufacturiersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VenteMobile.Data;
using VenteMobile.Models;

namespace VenteMobile.Controllers
{
    public class VendeurManufacturiersController : Controller
    {
        private readonly VenteMobileContext _context;

        public VendeurManufacturiersController(VenteMobileContext context)
        {
            _context = context;
        }

        // GET: VendeurManufacturiers
        public async Task<IActionResult> Index()
        {
            var venteMobileContext = _context.VendeurManufacturier.Include(v => v.Manufacturier).Include(v => v.Vendeur);
            return View(await venteMobileContext.ToListAsync());
        }
        public async Task<IActionResult> List(int vendeurId)
        {
            if (vendeurId == 0)
            {
                vendeurId = Convert.ToInt32(TempData["idV"]);
            }
            ViewBag.Vendeurs = await _context.Vendeur.FirstOrDefaultAsync(v => v.VendeurId == vendeurId);
            var venteMobileContext = _context.VendeurManufacturier.Include(v => v.Manufacturier).Include(v => v.Vendeur).Where(v => v.VendeurId == vendeurId);
            return View(await venteMobileContext.ToListAsync());
        }

        public async Task<IActionResult> CreateVendeurManufacturierss(int vendeurId)
        {
            ViewBag.Manufacturier = _context.Manufacturier;
            Vendeur vendeur = await _context.Vendeur.FirstOrDefaultAsync(v => v.VendeurId == vendeurId);
            TempData["idV"] = vendeur.VendeurId;
            return View(vendeur);
        }

        [HttpPost]
        public async Task<IActionResult> CreateVendeurManufacturierss(int vendeurId, int[] ManufacturierIds)
        {
            vendeurId = Convert.ToInt32(TempData["idV"]);
            foreach (int ManufId in ManufacturierIds)
            {
                VendeurManufacturier vendeurManufacturier = await _context.VendeurManufacturier
                .Include(v => v.Manufacturier)
                .Include(v => v.Vendeur)
                .FirstOrDefaultAsync(m => m.VendeurId == vendeurId && m.ManufacturierId == ManufId);
                if (vendeurManufacturier == null)
                {
                    vendeurManufacturier = new VendeurManufacturier
                    {
                        ManufacturierId = ManufId,
                        VendeurId = vendeurId
                    };
                    _context.VendeurManufacturier.Add(vendeurManufacturier);
                    await _context.SaveChangesAsync();
                }
            }
            return RedirectToAction("List", new { id = vendeurId });
        }


        // GET: VendeurManufacturiers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vendeurManufacturier = await _context.VendeurManufacturier
                .Include(v => v.Manufacturier)
                .Include(v => v.Vendeur)
                .FirstOrDefaultAsync(m => m.ManufacturierId == id);
            if (vendeurManufacturier == null)
            {
                return NotFound();
            }

            return View(vendeurManufacturier);
        }

        // GET: VendeurManufacturiers/Create
        public IActionResult Create()
        {
            ViewData["ManufacturierId"] = new SelectList(_context.Manufacturier, "ManufacturierId", "ManufacturierMarque");
            ViewData["idV"] = new SelectList(_context.Vendeur, "VendeurId", "VendeurNom");
            return View();
        }

        // POST: VendeurManufacturiers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("VendeurId,ManufacturierId")] VendeurManufacturier vendeurManufacturier)
        {
            if (ModelState.IsValid)
            {
                _context.Add(vendeurManufacturier);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ManufacturierId"] = new SelectList(_context.Manufacturier, "ManufacturierId", "ManufacturierMarque", vendeurManufacturier.ManufacturierId);
            ViewData["idV"] = new SelectList(_context.Vendeur, "VendeurId", "VendeurNom", vendeurManufacturier.VendeurId);
            return View(vendeurManufacturier);
        }

        // GET: VendeurManufacturiers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vendeurManufacturier = await _context.VendeurManufacturier.FindAsync(id);
            if (vendeurManufacturier == null)
            {
                return NotFound();
            }
            ViewData["ManufacturierId"] = new SelectList(_context.Manufacturier, "ManufacturierId", "ManufacturierMarque", vendeurManufacturier.ManufacturierId);
            ViewData["idV"] = new SelectList(_context.Vendeur, "VendeurId", "VendeurNom", vendeurManufacturier.VendeurId);
            return View(vendeurManufacturier);
        }

        // POST: VendeurManufacturiers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("VendeurId,ManufacturierId")] VendeurManufacturier vendeurManufacturier)
        {
            if (id != vendeurManufacturier.ManufacturierId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(vendeurManufacturier);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VendeurManufacturierExists(vendeurManufacturier.ManufacturierId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ManufacturierId"] = new SelectList(_context.Manufacturier, "ManufacturierId", "ManufacturierMarque", vendeurManufacturier.ManufacturierId);
            ViewData["idV"] = new SelectList(_context.Vendeur, "VendeurId", "VendeurNom", vendeurManufacturier.VendeurId);
            return View(vendeurManufacturier);
        }

        // GET: VendeurManufacturiers/Delete/5
        public async Task<IActionResult> Delete(int? idV, int? idM)
        {
            if (idV == null || idM == null)
            {
                return NotFound();
            }

            var vendeurManufacturier = await _context.VendeurManufacturier
                .Include(v => v.Manufacturier)
                .Include(v => v.Vendeur)
                .FirstOrDefaultAsync(m => m.ManufacturierId == idM && m.VendeurId == idV);
            if (vendeurManufacturier == null)
            {
                return NotFound();
            }

            TempData["idV"] = idV;
            TempData["idM"] = idM;
            return View(vendeurManufacturier);
        }

        // POST: VendeurManufacturiers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int idV, int idM)
        {

            idV = Convert.ToInt32(TempData["idV"]);
            idM = Convert.ToInt32(TempData["idM"]);
            var vendeurManufacturier = await _context.VendeurManufacturier
                .Include(v => v.Manufacturier)
                .Include(v => v.Vendeur)
                .FirstOrDefaultAsync(m => m.ManufacturierId == idM && m.VendeurId == idV);
            _context.VendeurManufacturier.Remove(vendeurManufacturier);
            await _context.SaveChangesAsync();
            return RedirectToAction("List", new { id = idV });
        }

        private bool VendeurManufacturierExists(int id)
        {
            return _context.VendeurManufacturier.Any(e => e.ManufacturierId == id);
        }
    }
}

VenteMobile/VenteMobile/Views/Manufacturiers/Create.cshtml
@model VenteMobile.Models.Manufacturier

@{
    ViewData["Title"] = "Create";
}

<h3 style="text-align:center"><B>Ajouter une Manufacturier</B></h3>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ManufacturierMarque" class="control-label"><B>Marque</B></label>
                <input asp-for="ManufacturierMarque" class="form-control" />
                <span asp-validation-for="ManufacturierMarque" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ManufacturierSiteWeb" class="control-label"><B>SiteWeb</B></label>
                <input asp-for="ManufacturierSiteWeb" class="form-control" />
                <span asp-validation-for="ManufacturierSiteWeb" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ManufacturierOrigine" class="control-label"><B>Siège social</B></label>
                <input asp-for="ManufacturierOrigine" class="form-control" />
                <span asp-validation-for="ManufacturierOrigine" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Créer" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Retour à la liste</a>
</div>
@section Scripts{

    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

VenteMobile/VenteMobile/Views/Manufacturiers/Delete.cshtml
@model VenteMobile.Models.Manufacturier

@{
    ViewData["Title"] = "Delete";
}

<h3 style="text-align:center"><B>Supprimer Manufacturier</B></h3>
<h3>Voulez vous vraiment le supprimer?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @*@Html.DisplayNameFor(model => model.ManufacturierMarque)*@
            Marque
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ManufacturierMarque)
        </dd>
        <dt class="col-sm-2">
            @*@Html.DisplayNameFor(model => model.ManufacturierSiteWeb)*@
            SiteWeb
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ManufacturierSiteWeb)
        </dd>
        <dt class="col-sm-2">
            @*@Html.DisplayNameFor(model => model.ManufacturierOrigine)*@
            Siège social
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ManufacturierOrigine)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="ManufacturierId" />
        <input type="submit" value="Supprimer" class="btn btn-danger" /> |
        <a asp-action="Index">Retour à la liste</a>
    </form>
</div>

VenteMobile/VenteMobile/Views/Manufacturiers/Detail.cshtml
@model VenteMobile.Models.Manufacturier

@{
    ViewData["Title"] = "Detail";
}
<h3 style="text-align:center"><B>Details  @Html.DisplayFor(model => model.ManufacturierMarque)</B></h3>
<div>

    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @*@Html.DisplayNameFor(model => model.ManufacturierMarque)*@
            Marque
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ManufacturierMarque)
        </dd>
        <dt class="col-sm-2">
            @*@Html.DisplayNameFor(model => model.ManufacturierSiteWeb)*@
            SiteWeb
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ManufacturierSiteWeb)
        </dd>
        <dt class="col-sm-2">
            @*@Html.DisplayNameFor(model => model.ManufacturierOrigine)*@
            Siège social
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ManufacturierOrigine)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Cliquer ici pour revenir", "List", "VendeurManufacturiers", new { vendeurId = ((Vendeur)ViewBag.Vendeur).VendeurId })
</div>

VenteMobile/VenteMobile/Views/Manufacturiers/Details.cshtml
@model VenteMobile.Models.Manufacturier

@{
    ViewData["Title"] = "Details";
}

<h3 style="text-align:center"><B>Details Manufacturier</B></h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @*@Html.DisplayNameFor(model => model.ManufacturierMarque)*@
            Marque
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ManufacturierMarque)
        </dd>
        <dt class="col-sm-2">
            @*@Html.DisplayNameFor(model => model.ManufacturierSiteWeb)*@
            SiteWeb
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ManufacturierSiteWeb)
        </dd>
        <dt class="col-sm-2">
            @*@Html.DisplayNameFor(model => model.ManufacturierOrigine)*@
            Siège social
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ManufacturierOrigine)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ManufacturierId">Edit</a> |
    <a asp-action="Index">Retour à la liste</a>
</div>

VenteMobile/VenteMobile/Views/Manufacturiers/Edit.cshtml
@model VenteMobile.Models.Manufacturier

@{
    ViewData["Title"] = "Edit";
}

<h3 style="text-align:center"><B> Modifier Manufacturier</B></h3>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ManufacturierId" />
            <div class="form-group">
                <label asp-for="ManufacturierMarque" class="control-label"><B>Marque</B></label>
                <input asp-for="ManufacturierMarque" class="form-control" />
                <span asp-validation-for="ManufacturierMarque" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ManufacturierSiteWeb" class="control-label"><B>SiteWeb</B></label>
                <input asp-for="ManufacturierSiteWeb" class="form-control" />
                <span asp-validation-for="ManufacturierSiteWeb" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ManufacturierOrigine" class="control-label"><B>Siège social</B></label>
                <input asp-for="ManufacturierOrigine" class="form-control" />
                <span asp-validation-for="ManufacturierOrigine" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Sauvegarder" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Retour à la liste</a>
</div>
@section Scripts{

    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

VenteMobile/VenteMobile/Views/Manufacturiers/Index.cshtml
@model PagedList.IPagedList<VenteMobile.Models.Manufacturier>
@using PagedList.Mvc;
@using PagedList;


@{
    ViewData["Title"] = "Index";
}

<div class="container jumbotron alert-success text-center table-bordered" style="position:relative ; top:50px; z-index:100; border-color:black;">
    <h3 style="text-align:center"><B> Liste Des Manufacturier</B></h3>
    <p>
        <a href="@Url.Action("Create")" class="btn btn-info btn-lg">
            <span class="glyphicon glyphicon-plus"></span>Ajouter
        </a>
    </p>
</div>
<div class="row container form-inline">
    <div class="pull-right input-group" style="margin-top:22px;">
        @using (Html.BeginForm("Index", "Manufacturiers", FormMethod.Get))
        {

            @Html.TextBox("searchString", ViewBag.currentFilter as string, new
            {
                @class = "form-control",
                @placeholder = "Rechercher"
            })

            <button type="submit" class="btn input-group-addon"><i class="glyphicon glyphicon-search" style="padding:3px;"></i></button>

        }
    </div>
</div>
<div class="row container form-inline">
    <span class="input-group ">Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) de @Model.PageCount</span>
</div>
@if (Model.Count == 0)
{
    <div class="alert-danger  jumbotron conainter table-bordered text-center" style="margin-top:60px; margin-bottom:10px;">
        Aucun telephone disponible avec le filtre n'a &eacute;t&eacute; utilis&eacute;
    </div>
    <a href="@Url.Action("Index","Manufacturier")" class="btn  btnStyle" style="background-color:cornflowerblue; width:120px;">Back to List</a>

    return;
}


<table class="table table-striped">
    <thead>
        <tr>
            <th style="text-align:center">
                @*@Html.DisplayNameFor(model => model.ManufacturierMarque)*@
                Marque
            </th>
            <th style="text-align:center">
                @*@Html.DisplayNameFor(model => model.ManufacturierSiteWeb)*@
                Site Web
            </th>
            <th style="text-align:center">
                @*@Html.DisplayNameFor(model => model.ManufacturierOrigine)*@
                Siège social
            </th>
            <th style="text-align:center">
                Opérations
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.ManufacturierMarque)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.ManufacturierSiteWeb)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.ManufacturierOrigine)
                </td>
                <td style="text-align:center">
                    <a href="@Url.Action("Edit",new {id = item.ManufacturierId})" class="btn btn-info btn-lg">
                        <span class="glyphicon glyphicon-edit"></span>
                    </a> |
                    <a href="@Url.Action("Details",new {id = item.ManufacturierId})" class="btn btn-info btn-lg">
                        <span class="glyphicon glyphicon-list"></span>
                    </a> |
                    <a href="@Url.Action("Delete", new {id = item.ManufacturierId})" class="btn btn-info btn-lg">
                        <span class="glyphicon glyphicon-trash"></span>
                    </a>

                </td>
            </tr>
        }
    </tbody>
</table>