VenteMobile/VenteMobile/Models/Telephone.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace VenteMobile.Models
{
    public class Telephone
       : IDisposable
    {
        private bool _disposed = false;
        public int TelephoneId { get; set; }
        [Required(ErrorMessage = "Le champs est obligatoire")]
        [DataType(DataType.Text)]
        [Display(Name = "Modèle")]
        public string TelephoneModel { get; set; }
        [Required(ErrorMessage = "Le champs est obligatoire")]
        [RegularExpression(@"^[0-9]+(\.[0-9]{1,2})?$", ErrorMessage = "Seul les chiffre entier ou 2 chiffre apres le 1 est autorisé")]
        [Display(Name = "Prix")]
        public double TelephoneCout { get; set; }
        [Required(ErrorMessage = "Le champs est obligatoire")]
        [DataType(DataType.Text)]
        [RegularExpression("[a-zA-Z][a-zA-Z ]+[a-zA-Z]$", ErrorMessage = "Seul les alphabets avec des espaces sont autorisés")]
        [Display(Name = "Couleur")]
        public string TelephoneCouleur { get; set; }
        public int ManufacturierId { get; set; }
        public Manufacturier Manufacturier { get; set; }
        public ICollection<TelephoneVendeur> TelephonesVendeurs { get; set; } = new HashSet<TelephoneVendeur>();
        public ICollection<Critique> Critiques { get; set; } = new HashSet<Critique>();
        ~Telephone()
        {
            Dispose(false);
        }
        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }
        private void Dispose(bool disposing)
        {
            if (!_disposed)
            {
                if (disposing)
                {

                }
            }
            _disposed = true;
        }
    }
}

VenteMobile/VenteMobile/Controllers/CritiquesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VenteMobile.Data;
using VenteMobile.Models;

namespace VenteMobile.Controllers
{
    public class CritiquesController : Controller
    {
        private readonly VenteMobileContext _context;

        public CritiquesController(VenteMobileContext context)
        {
            _context = context;
        }

        // GET: Critiques
        public async Task<IActionResult> Index()
        {
            var venteMobileContext = _context.Critique.Include(c => c.Telephone);
            return View(await venteMobileContext.ToListAsync());
        }

        // GET: Critiques/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var critique = await _context.Critique
                .Include(c => c.Telephone)
                .FirstOrDefaultAsync(m => m.CritiqueId == id);
            if (critique == null)
            {
                return NotFound();
            }

            return View(critique);
        }

        // GET: Critiques/Create
        public IActionResult Create(int id)
        {
            //ViewData["TelephoneId"] = new SelectList(_context.Set<Telephone>(), "TelephoneId", "TelephoneModel");
            ViewData["TelephoneId"] = id;
            return View();
        }

        // POST: Critiques/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CritiqueId,CritiqueText,CritiqueEtoiles,CritiqueNom,TelephoneId")] Critique critique)
        {
            if (ModelState.IsValid)
            {
                _context.Add(critique);
                await _context.SaveChangesAsync();
                //return RedirectToAction(nameof(Index));
                return RedirectToAction("Details", "Telephones", new { id = critique.TelephoneId });
            }
            //ViewData["TelephoneId"] = new SelectList(_context.Set<Telephone>(), "TelephoneId", "TelephoneModel", critique.TelephoneId);
            return View(critique);
        }

        // GET: Critiques/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var critique = await _context.Critique.FindAsync(id);
            if (critique == null)
            {
                return NotFound();
            }
            ViewData["TelephoneId"] = new SelectList(_context.Set<Telephone>(), "TelephoneId", "TelephoneModel", critique.TelephoneId);
            return View(critique);
        }

        // POST: Critiques/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CritiqueId,CritiqueText,CritiqueEtoiles,CritiqueNom,TelephoneId")] Critique critique)
        {
            if (id != critique.CritiqueId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(critique);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CritiqueExists(critique.CritiqueId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details", "Telephones", new { id = critique.TelephoneId });
            }
            ViewData["TelephoneId"] = new SelectList(_context.Set<Telephone>(), "TelephoneId", "TelephoneModel", critique.TelephoneId);
            return View(critique);
        }

        // GET: Critiques/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var critique = await _context.Critique
                .Include(c => c.Telephone)
                .FirstOrDefaultAsync(m => m.CritiqueId == id);
            if (critique == null)
            {
                return NotFound();
            }

            return View(critique);
        }

        // POST: Critiques/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var critique = await _context.Critique.FindAsync(id);
            _context.Critique.Remove(critique);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "Telephones", new { id = critique.TelephoneId });
        }

        private bool CritiqueExists(int id)
        {
            return _context.Critique.Any(e => e.CritiqueId == id);
        }
    }
}

VenteMobile/VenteMobile/Controllers/TelephonesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PagedList;
using VenteMobile.Data;
using VenteMobile.Models;

namespace VenteMobile.Controllers
{
    public class TelephonesController : Controller
    {
        private readonly VenteMobileContext _context;

        public TelephonesController(VenteMobileContext context)
        {
            _context = context;
        }

        // GET: Telephones
        public async Task<IActionResult> Index(int? page, string sortOrder, string searchString, string currentFilter)
        {

            ViewBag.CurrentSort = sortOrder;
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            var telephones = await Task.Run(() => _context.Telephone.Include(x => x.Manufacturier));
            List<Telephone> telephonesSearch = null;
            if (!string.IsNullOrEmpty(searchString))
            {

                telephonesSearch = await Task.Run(() => _context.Telephone.Include(x => x.Manufacturier).Where(z => z.TelephoneModel.Contains(searchString)).ToListAsync());
            }

            ViewBag.CurrentFilter = searchString;

            int pageSize = 50;
            int pageNumber = (page ?? 1);
            if (telephonesSearch != null)
            {
                return View(telephonesSearch.ToPagedList(pageNumber, pageSize));
            }
            return View(telephones.ToPagedList(pageNumber, pageSize));


        }

        // GET: Telephones/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var telephone = await _context.Telephone
                .Include(t => t.Manufacturier).Include(c => c.Critiques)
                .FirstOrDefaultAsync(m => m.TelephoneId == id);
            if (telephone == null)
            {
                return NotFound();
            }

            return View(telephone);
        }

        public async Task<IActionResult> Detail(int? idT, int? idV)
        {
            ViewBag.Vendeur = await _context.Vendeur.FirstOrDefaultAsync(v => v.VendeurId == idV);
            if (idT == null)
            {
                return NotFound();
            }

            var telephone = await _context.Telephone
             .Include(t => t.Manufacturier).Include(c => c.Critiques)
                .FirstOrDefaultAsync(m => m.TelephoneId == idT);
            if (telephone == null)
            {
                return NotFound();
            }

            return View(telephone);
        }

        // GET: Telephones/Create
        public IActionResult Create()
        {
            ViewData["ManufacturierId"] = new SelectList(_context.Manufacturier, "ManufacturierId", "ManufacturierMarque");
            return View();
        }

        // POST: Telephones/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TelephoneId,TelephoneModel,TelephoneCout,TelephoneCouleur,ManufacturierId,ManufacturierMarque")] Telephone telephone)
        {
            if (ModelState.IsValid)
            {
                _context.Add(telephone);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ManufacturierId"] = new SelectList(_context.Manufacturier, "ManufacturierId", "ManufacturierMarque", telephone.ManufacturierId);
            return View(telephone);
        }

        // GET: Telephones/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var telephone = await _context.Telephone.FindAsync(id);
            if (telephone == null)
            {
                return NotFound();
            }
            ViewData["ManufacturierId"] = new SelectList(_context.Manufacturier, "ManufacturierId", "ManufacturierMarque", telephone.ManufacturierId);
            return View(telephone);
        }

        // POST: Telephones/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TelephoneId,TelephoneModel,TelephoneCout,TelephoneCouleur,ManufacturierId")] Telephone telephone)
        {
            if (id != telephone.TelephoneId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(telephone);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TelephoneExists(telephone.TelephoneId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ManufacturierId"] = new SelectList(_context.Manufacturier, "ManufacturierId", "ManufacturierMarque", telephone.ManufacturierId);
            return View(telephone);
        }

        // GET: Telephones/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var telephone = await _context.Telephone
                .Include(t => t.Manufacturier)
                .FirstOrDefaultAsync(m => m.TelephoneId == id);
            if (telephone == null)
            {
                return NotFound();
            }

            return View(telephone);
        }

        // POST: Telephones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var telephone = await _context.Telephone.FindAsync(id);
            _context.Telephone.Remove(telephone);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TelephoneExists(int id)
        {
            return _context.Telephone.Any(e => e.TelephoneId == id);
        }
    }
}

VenteMobile/VenteMobile/Views/Telephones/Create.cshtml
@model VenteMobile.Models.Telephone

@{
    ViewData["Title"] = "Create";
}

<h3 style="text-align:center"><B>Ajouter un telephone</B></h3>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TelephoneModel" class="control-label"><B>Modèle</B></label>
                <input asp-for="TelephoneModel" class="form-control" />
                <span asp-validation-for="TelephoneModel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TelephoneCout" class="control-label"><B>Prix</B></label>
                <input asp-for="TelephoneCout" class="form-control" />
                <span asp-validation-for="TelephoneCout" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TelephoneCouleur" class="control-label"><B>Couleur</B></label>
                <input asp-for="TelephoneCouleur" class="form-control" />
                <span asp-validation-for="TelephoneCouleur" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Manufacturier" class="control-label"><B>Fabriquant</B></label>
                <select asp-for="ManufacturierId" class="form-control" asp-items="ViewBag.ManufacturierId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Créer" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Retour à la liste</a>
</div>
@section Scripts{

    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

VenteMobile/VenteMobile/Views/Telephones/Delete.cshtml
@model VenteMobile.Models.Telephone

@{
    ViewData["Title"] = "Delete";
}

<div style="margin-top:60px; margin-bottom:10px;">
    <h4 class="text-center table-bordered alert-danger" style="border-radius:5px; border-color:red; padding:10px;">Voulez vous vraiment supprimer ce telephone?</h4>
    <dl class="dl-horizontal table-bordered jumbotron alert-danger " style="color:black;border-color:red;">
        <dt class="col-sm-2">


            @*@Html.DisplayNameFor(model => model.TelephoneModel)*@
            Modèle
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TelephoneModel)
        </dd>
        <dt class="col-sm-2">
            @*@Html.DisplayNameFor(model => model.TelephoneCout)*@
            Prix
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TelephoneCout)
        </dd>
        <dt class="col-sm-2">
            @*@Html.DisplayNameFor(model => model.TelephoneCouleur)*@
            Couleur
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TelephoneCouleur)
        </dd>
        <dt class="col-sm-2">
            @*@Html.DisplayNameFor(model => model.Manufacturier)*@
            Fabriquant
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Manufacturier.ManufacturierMarque)
        </dd>

    </dl>
    <form asp-action="Delete">
        <input type="hidden" asp-for="TelephoneId" />
        <input type="submit" value="Supprimer" style="width:120px; background-color:red;" class="btn-danger btnStyle" /> |
        <a href="@Url.Action("Index","telephones")" class="btn  btnStyle" style="background-color:cornflowerblue; width:120px;">Retour</a>
    </form>
</div>


VenteMobile/VenteMobile/Views/Telephones/Detail.cshtml
@model VenteMobile.Models.Telephone

@{
    ViewData["Title"] = "Detail";
}

<h3 style="text-align:center"><B>Details  @Html.DisplayFor(model => model.TelephoneModel)</B></h3>

<div>

    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @*@Html.DisplayNameFor(model => model.TelephoneModel)*@
            Modèle
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TelephoneModel)
        </dd>
        <dt class="col-sm-2">
            @*@Html.DisplayNameFor(model => model.TelephoneCout)*@
            Prix
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TelephoneCout)
        </dd>
        <dt class="col-sm-2">
            @*@Html.DisplayNameFor(model => model.TelephoneCouleur)*@
            Couleur
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TelephoneCouleur)
        </dd>
        <dt class="col-sm-2">
            @*@Html.DisplayNameFor(model => model.Manufacturier)*@
            Fabriquant
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Manufacturier.ManufacturierMarque)
        </dd>
    </dl>
</div>
<div>
    @*<a asp-controller="Critiques" asp-action="Create" asp-route-id="@Model.TelephoneId">Ajouter une Critique</a>*@
    <h3 style="text-align:center"><B> Liste Des Critiques</B></h3>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    @*@Html.DisplayNameFor(model => model.CritiqueText)*@
                    Commentaire
                </th>
                <th>
                    @*@Html.DisplayNameFor(model => model.CritiqueEtoiles)*@
                    Etoiles
                </th>
                <th>
                    @*@Html.DisplayNameFor(model => model.CritiqueNom)*@
                    Client
                </th>
                <th>
                    @*@Html.DisplayNameFor(model => model.Telephone)*@
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Critiques)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.CritiqueText)
                    </td>
                    <td>
                        @for (int etoile = 0; etoile < (item.CritiqueEtoiles); etoile++)
                        {
                            <span class="glyphicon glyphicon-star"></span>
                        }
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CritiqueNom)
                    </td>
                    <td>
                        @*@Html.DisplayFor(modelItem => item.Telephone.TelephoneModel)*@
                    </td>
                    @*<td>
                            <a asp-controller="Critiques" asp-action="Edit" asp-route-id="@item.CritiqueId">Edit</a> |
                            <a asp-controller="Critiques" asp-action="Details" asp-route-id="@item.CritiqueId">Details</a> |
                            <a asp-controller="Critiques" asp-action="Delete" asp-route-id="@item.CritiqueId">Delete</a>
                        </td>*@
                </tr>
            }
        </tbody>
    </table>


</div>
<div>
    @Html.ActionLink("Cliquer ici pour revenir", "List", "TelephoneVendeurs", new { vendeurId = ((Vendeur)ViewBag.Vendeur).VendeurId })
</div>

VenteMobile/VenteMobile/Views/Telephones/Details.cshtml
@model VenteMobile.Models.Telephone

@{
    ViewData["Title"] = "Details";
}


<h4 class="text-center table-bordered alert-success" style="border-radius:5px; padding:10px;">Informations sur le telephone</h4>
<dl style="color:black;background-color:aquamarine">

    <div>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @*@Html.DisplayNameFor(model => model.TelephoneModel)*@
                Modèle
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.TelephoneModel)
            </dd>
            <dt class="col-sm-2">
                @*@Html.DisplayNameFor(model => model.TelephoneCout)*@
                Prix
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.TelephoneCout)
            </dd>
            <dt class="col-sm-2">
                @*@Html.DisplayNameFor(model => model.TelephoneCouleur)*@
                Couleur
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.TelephoneCouleur)
            </dd>
            <dt class="col-sm-2">
                @*@Html.DisplayNameFor(model => model.Manufacturier)*@
                Fabriquant
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Manufacturier.ManufacturierMarque)
            </dd>
        </dl>
</dl>

<div>
    <a asp-controller="Critiques" asp-action="Create" asp-route-id="@Model.TelephoneId">Ajouter une Critique</a>
    <h3 style="text-align:center"><B> Liste Des Critiques</B></h3>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    @*@Html.DisplayNameFor(model => model.CritiqueText)*@
                    Commentaire
                </th>
                <th>
                    @*@Html.DisplayNameFor(model => model.CritiqueEtoiles)*@
                    Etoiles
                </th>
                <th>
                    @*@Html.DisplayNameFor(model => model.CritiqueNom)*@
                    Client
                </th>
                <th>
                    @*@Html.DisplayNameFor(model => model.Telephone)*@
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Critiques)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.CritiqueText)
                    </td>
                    <td>
                        @for (int etoile = 0; etoile < (item.CritiqueEtoiles); etoile++)
                        {
                            <span class="glyphicon glyphicon-star"></span>
                        }
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CritiqueNom)
                    </td>
                    <td>
                        @*@Html.DisplayFor(modelItem => item.Telephone.TelephoneModel)*@
                    </td>
                    <td>
                        <a asp-controller="Critiques" asp-action="Edit" asp-route-id="@item.CritiqueId" class="btn btn-info btn-lg">
                            <span class="glyphicon glyphicon-edit"></span>
                        </a> |
                        <a asp-controller="Critiques" asp-action="Details" asp-route-id="@item.CritiqueId" class="btn btn-info btn-lg">
                            <span class="glyphicon glyphicon-list"></span>
                        </a> |
                        <a asp-controller="Critiques" asp-action="Delete" asp-route-id="@item.CritiqueId" class="btn btn-info btn-lg">
                            <span class="glyphicon glyphicon-trash"></span>
                        </a>
                </tr>
            }
        </tbody>
    </table>
</div>
    </div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.TelephoneId" class="btn  btnStyle" style="background-color:gray; width:120px;">Edit</a> |
    <a asp-action="Index" class="btn  btnStyle" style="background-color:cornflowerblue; width:120px;">Retour</a>

</div>

VenteMobile/VenteMobile/Views/Telephones/Edit.cshtml
@model VenteMobile.Models.Telephone

@{
    ViewData["Title"] = "Edit";
}


<h4 class="text-center table-bordered alert-success" style="border-radius:5px; padding:10px;">Changer les informations de vendeur</h4>
<div style="color:black;background-color:aquamarine">
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">

                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="TelephoneId" />
                <div class="form-group">
                    <div class="form-group">
                        <label asp-for="TelephoneModel" class="control-label"><B>Modèle</B></label>
                        <input asp-for="TelephoneModel" class="form-control" />
                        <span asp-validation-for="TelephoneModel" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="TelephoneCout" class="control-label"><B>Prix</B></label>
                        <input asp-for="TelephoneCout" class="form-control" />
                        <span asp-validation-for="TelephoneCout" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="TelephoneCouleur" class="control-label"><B>Couleur</B></label>
                        <input asp-for="TelephoneCouleur" class="form-control" />
                        <span asp-validation-for="TelephoneCouleur" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ManufacturierId" class="control-label"><B>Fabriquant</B></label>
                        <select asp-for="ManufacturierId" class="form-control" asp-items="ViewBag.ManufacturierId"></select>
                        <span asp-validation-for="ManufacturierId" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" class="btn  btnStyle" style="background-color:green; width:120px;" value="Sauvegarder" /> |
                        <a href="@Url.Action("Index","telephones")" class="btn  btnStyle" style="background-color:cornflowerblue; width:120px;">Retour</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div>
    </div>
</div>
@section Scripts{

    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}