VenteMobile/VenteMobile/Models/Vendeur.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace VenteMobile.Models
{
    public class Vendeur
        : IDisposable
    {
        private bool _disposed = false;
        public int VendeurId { get; set; }
        [Required(ErrorMessage = "Le champs est obligatoire")]
        [DataType(DataType.Text)]
        [RegularExpression("[a-zA-Z][a-zA-Z ]+[a-zA-Z]$", ErrorMessage = "Seul les alphabets avec des espaces sont autorisés")]
        [Display(Name = "Nom")]
        public string VendeurNom { get; set; }
        [Required(ErrorMessage = "Le champs est obligatoire")]
        [DataType(DataType.Text)]
        [Display(Name = "Address")]
        public string VendeurAddress { get; set; }
        [Required(ErrorMessage = "Le champs est obligatoire")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression("[(][0-9]{3}[)][ ][0-9]{3}[-][0-9]{4}", ErrorMessage = "Entrer un numero de telephone valide (###) ###-####")]
        [Display(Name = "NoTel")]
        public string VendeurNoTel { get; set; }
        public ICollection<TelephoneVendeur> TelephonesVendeurs { get; set; } = new HashSet<TelephoneVendeur>();
        public ICollection<VendeurManufacturier> VendeursManufacturiers { get; set; } = new HashSet<VendeurManufacturier>();
        ~Vendeur()
        {
            Dispose(false);
        }
        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }
        private void Dispose(bool disposing)
        {
            if (!_disposed)
            {
                if (disposing)
                {

                }
            }
            _disposed = true;
        }
    }
}

VenteMobile/VenteMobile/Controllers/TelephoneVendeursController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VenteMobile.Data;
using VenteMobile.Models;

namespace VenteMobile.Controllers
{
    public class TelephoneVendeursController : Controller
    {
        private readonly VenteMobileContext _context;

        public TelephoneVendeursController(VenteMobileContext context)
        {
            _context = context;
        }

        // GET: TelephoneVendeurs
        public async Task<IActionResult> Index()
        {


            var venteMobileContext = _context.TelephoneVendeur.Include(t => t.Telephone).Include(t => t.Vendeur);
            return View(await venteMobileContext.ToListAsync());

        }
        public async Task<IActionResult> List(int vendeurId, string searchString, string currentFilter)
        {
            if (vendeurId == 0)
            {
                vendeurId = Convert.ToInt32(TempData["idV"]);
            }
            ViewBag.Vendeurs = await _context.Vendeur.FirstOrDefaultAsync(v => v.VendeurId == vendeurId);
            var venteMobileContext = _context.TelephoneVendeur.Include(v => v.Telephone).Include(v => v.Vendeur).Where(v => v.VendeurId == vendeurId);
            return View(await venteMobileContext.ToListAsync());
        }
        public async Task<IActionResult> AjouterTelephone(int vendeurId)
        {
            ViewBag.VendeurManufacturier = _context.VendeurManufacturier.Include(v => v.Manufacturier).Include(v => v.Vendeur).Where(v => v.VendeurId == vendeurId);
            ViewBag.Telephone = _context.Telephone;
            Vendeur vendeur = await _context.Vendeur.FirstOrDefaultAsync(v => v.VendeurId == vendeurId);
            TempData["idV"] = vendeur.VendeurId;
            return View(vendeur);
        }

        [HttpPost]
        public async Task<IActionResult> AjouterTelephone(int vendeurId, int[] TelephoneIds)
        {
            vendeurId = Convert.ToInt32(TempData["idV"]);
            foreach (int TelId in TelephoneIds)
            {
                TelephoneVendeur telephoneVendeur = await _context.TelephoneVendeur
                .Include(t => t.Telephone)
                .Include(v => v.Vendeur)
                .FirstOrDefaultAsync(m => m.VendeurId == vendeurId && m.TelephoneId == TelId);
                if (telephoneVendeur == null)
                {
                    telephoneVendeur = new TelephoneVendeur
                    {
                        TelephoneId = TelId,
                        VendeurId = vendeurId
                    };
                    _context.TelephoneVendeur.Add(telephoneVendeur);
                    await _context.SaveChangesAsync();
                }
            }
            return RedirectToAction("List", new { id = vendeurId });
        }

        // GET: TelephoneVendeurs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var telephoneVendeur = await _context.TelephoneVendeur
                .Include(t => t.Telephone)
                .Include(t => t.Vendeur)
                .FirstOrDefaultAsync(m => m.TelephoneId == id);
            if (telephoneVendeur == null)
            {
                return NotFound();
            }

            return View(telephoneVendeur);
        }

        // GET: TelephoneVendeurs/Create
        public IActionResult Create()
        {
            ViewData["TelephoneId"] = new SelectList(_context.Telephone, "TelephoneId", "TelephoneModel");
            ViewData["VendeurId"] = new SelectList(_context.Vendeur, "VendeurId", "VendeurNom");
            return View();
        }

        // POST: TelephoneVendeurs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("VendeurId,TelephoneId")] TelephoneVendeur telephoneVendeur)
        {
            if (ModelState.IsValid)
            {
                _context.Add(telephoneVendeur);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["TelephoneId"] = new SelectList(_context.Telephone, "TelephoneId", "TelephoneModel", telephoneVendeur.TelephoneId);
            ViewData["VendeurId"] = new SelectList(_context.Vendeur, "VendeurId", "VendeurNom", telephoneVendeur.VendeurId);
            return View(telephoneVendeur);
        }

        // GET: TelephoneVendeurs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var telephoneVendeur = await _context.TelephoneVendeur.FindAsync(id);
            if (telephoneVendeur == null)
            {
                return NotFound();
            }
            ViewData["TelephoneId"] = new SelectList(_context.Telephone, "TelephoneId", "TelephoneModel", telephoneVendeur.TelephoneId);
            ViewData["VendeurId"] = new SelectList(_context.Vendeur, "VendeurId", "VendeurNom", telephoneVendeur.VendeurId);
            return View(telephoneVendeur);
        }

        // POST: TelephoneVendeurs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("VendeurId,TelephoneId")] TelephoneVendeur telephoneVendeur)
        {
            if (id != telephoneVendeur.TelephoneId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(telephoneVendeur);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TelephoneVendeurExists(telephoneVendeur.TelephoneId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["TelephoneId"] = new SelectList(_context.Telephone, "TelephoneId", "TelephoneModel", telephoneVendeur.TelephoneId);
            ViewData["VendeurId"] = new SelectList(_context.Vendeur, "VendeurId", "VendeurNom", telephoneVendeur.VendeurId);
            return View(telephoneVendeur);
        }

        // GET: TelephoneVendeurs/Delete/5
        public async Task<IActionResult> Delete(int? idV, int? idT)
        {
            if (idV == null || idT == null)
            {
                return NotFound();
            }

            var telephoneVendeur = await _context.TelephoneVendeur
                .Include(v => v.Telephone)
                .Include(v => v.Vendeur)
                .FirstOrDefaultAsync(m => m.TelephoneId == idT && m.VendeurId == idV);
            if (telephoneVendeur == null)
            {
                return NotFound();
            }

            TempData["idV"] = idV;
            TempData["idT"] = idT;
            return View(telephoneVendeur);
        }

        // POST: TelephoneVendeurs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int idV, int idT)
        {

            idV = Convert.ToInt32(TempData["idV"]);
            idT = Convert.ToInt32(TempData["idT"]);
            var telephoneVendeur = await _context.TelephoneVendeur
                .Include(v => v.Telephone)
                .Include(v => v.Vendeur)
                .FirstOrDefaultAsync(m => m.TelephoneId == idT && m.VendeurId == idV);
            _context.TelephoneVendeur.Remove(telephoneVendeur);
            await _context.SaveChangesAsync();
            return RedirectToAction("List", new { id = idV });
        }

        private bool TelephoneVendeurExists(int id)
        {
            return _context.TelephoneVendeur.Any(e => e.TelephoneId == id);
        }
    }
}

VenteMobile/VenteMobile/Controllers/VendeursController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VenteMobile.Data;
using VenteMobile.Models;
using PagedList;
using System.Web;


namespace VenteMobile.Controllers
{
    public class VendeursController : Controller
    {
        private readonly VenteMobileContext _context;

        public VendeursController(VenteMobileContext context)
        {
            _context = context;
        }

        // GET: Vendeurs
        public async Task<IActionResult> Index(int? page, string sortOrder, string searchString, string currentFilter)
        {
            ViewBag.CurrentSort = sortOrder;

            ViewBag.CurrentSort = sortOrder;
            ViewBag.NomSortParm = string.IsNullOrEmpty(sortOrder) ? "nom_desc" : "";

            ViewBag.AdresseSortParm = sortOrder == "Adresse" ? "adresse_desc" : "Adresse";
            ViewBag.NoTelSortParm = sortOrder == "NoTel" ? "noTel_desc" : "NoTel";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            var Vendeurs = await Task.Run(() => _context.Vendeur.Select(x => x));
            if (!string.IsNullOrEmpty(searchString))
            {
                Vendeurs = await Task.Run(() =>
                _context.Vendeur.Where(s => s.VendeurNom.Contains(searchString)));

            }

            switch (sortOrder)
            {
                case "nom_desc":
                    Vendeurs = await Task.Run(() => Vendeurs.OrderByDescending(s => s.VendeurNom));
                    break;
                case "prenom_desc":
                    Vendeurs = await Task.Run(() => Vendeurs.OrderByDescending(s => s.VendeurAddress));
                    break;
                case "adresse_desc":
                    Vendeurs = await Task.Run(() => Vendeurs.OrderByDescending(s => s.VendeurNoTel));
                    break;

                default:
                    Vendeurs = await Task.Run(() => Vendeurs.OrderBy(s => s.VendeurNom));
                    break;
            }


            ViewBag.CurrentFilter = searchString;

            int pageSize = 50;
            int pageNumber = (page ?? 1);
            return View(Vendeurs.ToPagedList(pageNumber, pageSize));

        }

        // GET: Vendeurs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vendeur = await _context.Vendeur
                .FirstOrDefaultAsync(m => m.VendeurId == id);
            if (vendeur == null)
            {
                return NotFound();
            }

            return View(vendeur);
        }

        // GET: Vendeurs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Vendeurs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("VendeurId,VendeurNom,VendeurAddress,VendeurNoTel")] Vendeur vendeur)
        {
            if (ModelState.IsValid)
            {
                _context.Add(vendeur);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(vendeur);
        }

        // GET: Vendeurs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vendeur = await _context.Vendeur.FindAsync(id);
            if (vendeur == null)
            {
                return NotFound();
            }
            return View(vendeur);
        }

        // POST: Vendeurs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("VendeurId,VendeurNom,VendeurAddress,VendeurNoTel")] Vendeur vendeur)
        {
            if (id != vendeur.VendeurId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(vendeur);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VendeurExists(vendeur.VendeurId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(vendeur);
        }

        // GET: Vendeurs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vendeur = await _context.Vendeur
                .FirstOrDefaultAsync(m => m.VendeurId == id);
            if (vendeur == null)
            {
                return NotFound();
            }

            return View(vendeur);
        }

        // POST: Vendeurs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var vendeur = await _context.Vendeur.FindAsync(id);
            _context.Vendeur.Remove(vendeur);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VendeurExists(int id)
        {
            return _context.Vendeur.Any(e => e.VendeurId == id);
        }
    }
}

VenteMobile/VenteMobile/Views/Vendeurs/Create.cshtml
@model VenteMobile.Models.Vendeur

@{
    ViewBag.Title = "Cree un vendeur";
    ViewBag.Icon = Url.Content("~/images/create.png");
}


@*<div class="form-horizontal" style="margin-top:60px; margin-bottom:10px;">
    <h4 class="text-center table-bordered alert-success" style="border-radius:5px; padding:10px;">Entrer les informations sur le vendeur</h4>
    <div class="dl-horizontal table-bordered jumbotron alert-info " style="color:black;">*@

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <div class="col-md-10">
                    <label asp-for="VendeurNom" class="control-label"><B>Nom</B></label>
                    <input asp-for="VendeurNom" class="form-control" />
                    <span asp-validation-for="VendeurNom" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-10">
                    <label asp-for="VendeurAddress" class="control-label"><B>Address</B></label>
                    <input asp-for="VendeurAddress" class="form-control" />
                    <span asp-validation-for="VendeurAddress" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-10">
                    <label asp-for="VendeurNoTel" class="control-label"><B>NoTel</B></label>
                    <input asp-for="VendeurNoTel" class="form-control" />
                    <span asp-validation-for="VendeurNoTel" class="text-danger"></span>
                </div>
            </div>

            <div class="col-md-10">
                @*<p>
                        <input type="submit" class="btn  btnStyle" style="background-color:green; width:120px;" value="Enregistrer" /> |
                        <a href="@Url.Action("Index","Vendeurs")" class="btn  btnStyle" style="background-color:cornflowerblue; width:120px;">Back to List</a>
                    </p>*@
                <p>
                    <input type="submit" class="btn btn-info" value="Créer" /> |
                    <a href="@Url.Action("Index","Vendeurs")" class="btn btn-info">Back to List</a>
                </p>

            </div>
        </form>
    </div>
</div>
@section Scripts{

    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

VenteMobile/VenteMobile/Views/Vendeurs/Delete.cshtml
@model VenteMobile.Models.Vendeur

@{
    ViewData["Title"] = "Delete";
}



<h3>Voulez vous vraiment le supprimer?</h3>

<hr />
<div style="margin-top:60px; margin-bottom:10px;">
    <h4 class="text-center table-bordered alert-danger" style="border-radius:5px; border-color:red; padding:10px;">Voulez vous vraiment supprimer ce vendeur?</h4>
    <dl class="dl-horizontal table-bordered jumbotron alert-danger " style="color:black;border-color:red;">
        <dt class="col-sm-2">
            @*@Html.DisplayNameFor(model => model.VendeurNom)*@
            Nom
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.VendeurNom)
        </dd>
        <dt class="col-sm-2">
            @*@Html.DisplayNameFor(model => model.VendeurAddress)*@
            Address
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.VendeurAddress)
        </dd>
        <dt class="col-sm-2">
            @*@Html.DisplayNameFor(model => model.VendeurNoTel)*@
            NoTel
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.VendeurNoTel)
        </dd>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Supprimer" style="width:120px; background-color:red;" class="btn-danger btnStyle" /> |
                <a class="btn btn-success btnStyle" style="width:120px; background-color:cornflowerblue;" href="@Url.Action("Index", "Vendeurs")">Retour </a>
            </div>
        }

</div>

</dl>

VenteMobile/VenteMobile/Views/Vendeurs/Details.cshtml
@model VenteMobile.Models.Vendeur

@{
    ViewData["Title"] = "Details";
}

<div style="margin-top:60px; margin-bottom:10px;">
    <h4 class="text-center table-bordered alert-success" style="border-radius:5px; padding:10px;">Informations sur le Vendeur</h4>
    <dl style="color:black;background-color:aqua">
        <div>
            <hr />
            <dl class="row">
                <dt class="col-sm-2">
                    @*@Html.DisplayNameFor(model => model.VendeurNom)*@
                    Nom
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.VendeurNom)
                </dd>
                <dt class="col-sm-2">
                    @*@Html.DisplayNameFor(model => model.VendeurAddress)*@
                    Address
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.VendeurAddress)
                </dd>
                <dt class="col-sm-2">
                    @*@Html.DisplayNameFor(model => model.VendeurNoTel)*@
                    NoTel
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.VendeurNoTel)
                </dd>
                <dt class="col-sm-2">
                    La liste des Manifacturier
                </dt>
                <dd class="col-sm-10">
                    @Html.ActionLink("Cliquer ici pour afficher la liste des manifacturier", "List", "VendeurManufacturiers", new { vendeurId = Model.VendeurId })
                </dd>
                <dt class="col-sm-2">
                    La liste des Telephones
                </dt>
                <dd class="col-sm-10">
                    @Html.ActionLink("Cliquer ici pour afficher la liste des Telephones", "List", "TelephoneVendeurs", new { vendeurId = Model.VendeurId })
                </dd>
            </dl>
        </div>
    </dl>

    <p>
        <a href="@Url.Action("Edit","Vendeurs",new { id = Model.VendeurId })" class="btn  btnStyle" style="background-color:gray; width:120px;">Edit</a> |
        <a href="@Url.Action("Index","Vendeurs")" class="btn  btnStyle" style="background-color:cornflowerblue; width:120px;">Retour</a>

    </p>


</div>

VenteMobile/VenteMobile/Views/Vendeurs/Edit.cshtml
@model VenteMobile.Models.Vendeur

@{
    ViewData["Title"] = "Edit";
}


<div class="form-horizontal" style="margin-top:60px; margin-bottom:10px;">
    <h4 class="text-center table-bordered alert-success" style="border-radius:5px; padding:10px;">Changer les informations de vendeur</h4>
    <div class="dl-horizontal table-bordered jumbotron alert-info " style="color:black;">
        <hr />
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="VendeurId" />
                    <div class="form-group">
                        <div class="col-md-10">
                            <label asp-for="VendeurNom" class="control-label"><B>Nom</B></label>
                            <input asp-for="VendeurNom" class="form-control" />
                            <span asp-validation-for="VendeurNom" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-10">
                            <label asp-for="VendeurAddress" class="control-label"><B>Address</B></label>
                            <input asp-for="VendeurAddress" class="form-control" />
                            <span asp-validation-for="VendeurAddress" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-10">
                            <label asp-for="VendeurNoTel" class="control-label"><B>NoTel</B></label>
                            <input asp-for="VendeurNoTel" class="form-control" />
                            <span asp-validation-for="VendeurNoTel" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group">

                        <p>
                            <input type="submit" class="btn  btnStyle" style="background-color:green; width:120px;" value="Sauvegarder" /> |
                            <a href="@Url.Action("Index","Vendeurs")" class="btn  btnStyle" style="background-color:cornflowerblue; width:120px;">Retour</a>

                        </p>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts{

    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}


VenteMobile/VenteMobile/Views/Vendeurs/Index.cshtml


@model PagedList.IPagedList<VenteMobile.Models.Vendeur>

@using PagedList.Mvc;
@using PagedList;



@{
    ViewData["Title"] = "Index";
}
<div class="container jumbotron alert-success text-center table-bordered" style="position:relative ; top:50px; z-index:100; border-color:black;">
    <h3 style="text-align:center"><B> Liste Des Vendeurs</B></h3>
    <p>
        <a href="@Url.Action("Create")" class="btn btn-info btn-lg">
            <span class="glyphicon glyphicon-plus"></span>Ajouter
        </a>
    </p>
</div>


<div class="row container form-inline" style="margin:2px" ;>
    <div class="pull-right input-group" style="margin-top:22px;">
        @using (Html.BeginForm("Index", "Vendeurs", FormMethod.Get))
        {

            @Html.TextBox("searchString", ViewBag.currentFilter as string, new
            {
                @class = "form-control",
                @placeholder = "Rechercher"
            })

            <button type="submit" class="btn input-group-addon"><i class="glyphicon glyphicon-search" style="padding:3px;"></i></button>

        }
    </div>
    <div class="row container form-inline">

        <span class="input-group ">Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) de @Model.PageCount</span>

    </div>


    @if (Model.Count == 0)
    {
        <div class="alert-danger  jumbotron conainter table-bordered text-center" style="margin-top:60px; margin-bottom:10px;">
            Aucun client disponible avec le filtre n'a &eacute;t&eacute; utilis&eacute;
        </div>
        <a href="@Url.Action("Index","Vendeurs")" class="btn  btnStyle" style="background-color:cornflowerblue; width:120px;">Back to List</a>

        return;
    }



</div>

<table class="table table-striped">
    <thead>
        <tr>

            <th style="text-align:center">
                @Html.ActionLink("Nom", "Index", new { sortOrder = ViewBag.NomSortParm })

            </th>
            <th style="text-align:center">
                @Html.ActionLink("Adresse", "Index", new { sortOrder = ViewBag.AdresseSortParm })
            </th>
            <th style="text-align:center">
                @Html.ActionLink("Téléphone", "Index", new { sortOrder = ViewBag.NoTelSortParm })
            </th>
            @*<th style="text-align:center">
                    Assigner les manifacturier
                </th>*@
            <th style="text-align:center">
                Opérations
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.VendeurNom)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.VendeurAddress)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(modelItem => item.VendeurNoTel)
                </td>
                @*<td style="text-align:center">
                        @Html.ActionLink("Assigner une manifacturier", "CreateVendeurManufacturierss", "VendeurManufacturiers", new { vendeurId = item.VendeurId })
                    </td>*@
                <td style="text-align:center">
                    <a href="@Url.Action("Edit",new {id = item.VendeurId})" class="btn btn-info btn-lg">
                        <span class="glyphicon glyphicon-edit"></span>
                    </a> |
                    <a href="@Url.Action("Details",new {id = item.VendeurId})" class="btn btn-info btn-lg">
                        <span class="glyphicon glyphicon-list"></span>
                    </a> |
                    <a href="@Url.Action("Delete", new {id = item.VendeurId})" class="btn btn-info btn-lg">
                        <span class="glyphicon glyphicon-trash"></span>
                    </a>
                </td>

            </tr>
        }
    </tbody>
</table>